### ISSUE TITLE
[Bug]: "npm install" missing in README.md file

### ISSUE THREAD

**Issue by Dev-Sambhav** [hiteshchoudhary/nextjs-fullstack-auth#49]
# Describe the Bug
In README.md file "npm install" should be executed before "npm run dev".

# To Reproduce
1. Click here [Repo](https://github.com/hiteshchoudhary/nextjs-fullstack-auth)
2. Scroll down until you see **Getting Started**
3. Now see "npm install" is missing

<img width="386" alt="image" src="https://github.com/hiteshchoudhary/nextjs-fullstack-auth/assets/95364492/2c2bcdb9-f81f-47d5-899c-1cc7013f1514">

# Expected behavior
Add "npm install" before "npm run dev"

**Comment by vaidik2626** [comment]
It s common Sense If you learn nextjs then Every person know that Things
